# Generated by Django 2.0.7 on 2018-07-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywebapp', '0003_auto_20180729_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='pywebapp.Author'),
        ),
        migrations.DeleteModel(
            name='Book_Author',
        ),
    ]
